import React from "react";
import "./feed.css";

export default function Feed() {
  return (
    <div className="feedContainer">
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
      <p>he content</p>
    </div>
  );
}
